language: javascript

install:
  - wget https://nodejs.org/dist/v8.11.3/node-v8.11.3-linux-x64.tar.xz && xz -d node-v8.11.3-linux-x64.tar.xz && tar -xvf node-v8.11.3-linux-x64.tar
  - 

cache:
  directories:
    - ./node_modules

matrix:
  include:
    - env:
      - TASK=build
      script: ./node-v8.9.0-linux-x64/bin/npm install

deploy:
  provider: script
  script: bash .deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST = "false" && $TASK = "build"
